import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Project from '../components/Project'
import Skills from '../components/Skills'
//import Image from 'next/image'
//import styles from '../styles/Home.module.css'
//Font Awesome Icons
//import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';


export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skills/>
      <Project/>
      <Contact/>
      
    </>
  )
}
