import Head from 'next/head';
import Contact from '../components/Contact';
import Main from '../components/Main';
import Project from '../components/Project';
import Skills from '../components/Skills';
import About from '../components/About';

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <About/>
      <Skills/>
      <Project/>
      <Contact/>
      
    </>
  )
}
